on:
  issues:
    types: [opened]
   
jobs:
  thank-user:
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    name: Say thanks for the Issue
    steps:
      - name: comment on the issue
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.CLI_BOT }}
          repository: 'Azure/azure-cli'
          number: ${{ github.event.issue.number }}
          id: thank-you-comment
          message: 'Thank you for opening this issue, we will look into it.'
