name: Run GitHub issue copilot
on:
  issues:
    types: [opened, edited, closed]

jobs:
  Issue-copilot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Run GitHub issue copilot
        uses: MoChilia/IssueCopilot@v0
        with:
          password: ${{secrets.COPILOT_PASSWORD}}
